USE [master]
GO
/****** Object:  Database [BD_Grupo1]    Script Date: 13/9/2020 20:01:04 ******/
CREATE DATABASE [BD_Grupo1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_Grupo1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BD_Grupo1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BD_Grupo1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BD_Grupo1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [BD_Grupo1] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_Grupo1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BD_Grupo1] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BD_Grupo1] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BD_Grupo1] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BD_Grupo1] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BD_Grupo1] SET ARITHABORT OFF 
GO
ALTER DATABASE [BD_Grupo1] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BD_Grupo1] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BD_Grupo1] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BD_Grupo1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BD_Grupo1] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BD_Grupo1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BD_Grupo1] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BD_Grupo1] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BD_Grupo1] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BD_Grupo1] SET  ENABLE_BROKER 
GO
ALTER DATABASE [BD_Grupo1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BD_Grupo1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BD_Grupo1] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BD_Grupo1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BD_Grupo1] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BD_Grupo1] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BD_Grupo1] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BD_Grupo1] SET RECOVERY FULL 
GO
ALTER DATABASE [BD_Grupo1] SET  MULTI_USER 
GO
ALTER DATABASE [BD_Grupo1] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BD_Grupo1] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BD_Grupo1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BD_Grupo1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BD_Grupo1] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'BD_Grupo1', N'ON'
GO
ALTER DATABASE [BD_Grupo1] SET QUERY_STORE = OFF
GO
USE [BD_Grupo1]
GO
/****** Object:  User [Grupo1]    Script Date: 13/9/2020 20:01:05 ******/
CREATE USER [Grupo1] FOR LOGIN [Grupo1] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  User [CI2400\admin]    Script Date: 13/9/2020 20:01:05 ******/
CREATE USER [CI2400\admin] FOR LOGIN [CI2400\admin] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [Grupo1]
GO
/****** Object:  Table [dbo].[Habilidades]    Script Date: 13/9/2020 20:01:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Habilidades](
	[Id] [int] NOT NULL,
	[Habilidad] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC,
	[Habilidad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Idiomas]    Script Date: 13/9/2020 20:01:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Idiomas](
	[Id] [int] NOT NULL,
	[Idioma] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC,
	[Idioma] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 13/9/2020 20:01:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[Id] [int] NOT NULL,
	[Genero] [char](1) NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[PrimerApellido] [nvarchar](50) NOT NULL,
	[SegundoApellido] [nvarchar](50) NULL,
	[Email] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[Nacionalidad] [nvarchar](50) NOT NULL,
	[Hobbies] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Habilidades]  WITH CHECK ADD  CONSTRAINT [FK_Habilidades_Usuario] FOREIGN KEY([Id])
REFERENCES [dbo].[Usuario] ([Id])
GO
ALTER TABLE [dbo].[Habilidades] CHECK CONSTRAINT [FK_Habilidades_Usuario]
GO
ALTER TABLE [dbo].[Idiomas]  WITH CHECK ADD  CONSTRAINT [FK_Idiomas_Usuario] FOREIGN KEY([Id])
REFERENCES [dbo].[Usuario] ([Id])
GO
ALTER TABLE [dbo].[Idiomas] CHECK CONSTRAINT [FK_Idiomas_Usuario]
GO
USE [master]
GO
ALTER DATABASE [BD_Grupo1] SET  READ_WRITE 
GO
